--- #YAML:1.0
name:                Want
version:             0.11
abstract:            ~
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_02
author:              ~
distribution_type:   module
requires:     
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
